/**
 * Módulo de Exportação de Geometria
 * Suporta formatos JSON, OBJ e STL
 */

/**
 * Exporta superfície para formato JSON
 * @param {Object} surfaceData - Dados da superfície {vertices, faces, normals, parameters}
 * @param {Object} profileData - Dados do perfil {controlPoints, curveType, degree}
 * @returns {string} JSON formatado
 */
export function exportToJSON(surfaceData, profileData) {
    const data = {
        metadata: {
            format: 'Revolution Surface',
            version: '1.0',
            date: new Date().toISOString(),
            generator: 'Questao02 - Surface of Revolution'
        },
        profile: {
            controlPoints: profileData.controlPoints,
            curveType: profileData.curveType,
            degree: profileData.degree,
            resolution: profileData.resolution
        },
        revolution: {
            axis: surfaceData.parameters.axis,
            angle: surfaceData.parameters.angle,
            subdivisions: surfaceData.parameters.subdivisions
        },
        geometry: {
            vertices: surfaceData.vertices,
            faces: surfaceData.faces,
            normals: surfaceData.normals
        },
        statistics: {
            vertexCount: surfaceData.vertices.length,
            faceCount: surfaceData.faces.length,
            triangleCount: surfaceData.faces.length
        }
    };

    return JSON.stringify(data, null, 2);
}

/**
 * Exporta superfície para formato Wavefront OBJ
 * @param {Object} surfaceData - Dados da superfície {vertices, faces, normals}
 * @param {string} objectName - Nome do objeto
 * @returns {string} Conteúdo OBJ
 */
export function exportToOBJ(surfaceData, objectName = 'RevolutionSurface') {
    let obj = `# Wavefront OBJ file\n`;
    obj += `# Generated by Questao02 - Surface of Revolution\n`;
    obj += `# Date: ${new Date().toISOString()}\n\n`;
    obj += `o ${objectName}\n\n`;

    // Vértices
    obj += `# ${surfaceData.vertices.length} vertices\n`;
    for (const v of surfaceData.vertices) {
        obj += `v ${v.x.toFixed(6)} ${v.y.toFixed(6)} ${v.z.toFixed(6)}\n`;
    }
    obj += '\n';

    // Normais
    obj += `# ${surfaceData.normals.length} vertex normals\n`;
    for (const n of surfaceData.normals) {
        obj += `vn ${n.x.toFixed(6)} ${n.y.toFixed(6)} ${n.z.toFixed(6)}\n`;
    }
    obj += '\n';

    // Faces (OBJ usa indexação 1-based)
    obj += `# ${surfaceData.faces.length} faces\n`;
    for (const face of surfaceData.faces) {
        const [i0, i1, i2] = face;
        // Formato: f v1//vn1 v2//vn2 v3//vn3
        obj += `f ${i0 + 1}//${i0 + 1} ${i1 + 1}//${i1 + 1} ${i2 + 1}//${i2 + 1}\n`;
    }

    return obj;
}

/**
 * Exporta superfície para formato STL (ASCII)
 * @param {Object} surfaceData - Dados da superfície {vertices, faces, normals}
 * @param {string} solidName - Nome do sólido
 * @returns {string} Conteúdo STL
 */
export function exportToSTL(surfaceData, solidName = 'RevolutionSurface') {
    let stl = `solid ${solidName}\n`;

    // Para cada face, escreve um triângulo
    for (const face of surfaceData.faces) {
        const [i0, i1, i2] = face;
        
        // Calcula a normal da face
        const v0 = surfaceData.vertices[i0];
        const v1 = surfaceData.vertices[i1];
        const v2 = surfaceData.vertices[i2];

        // Vetores das arestas
        const edge1 = {
            x: v1.x - v0.x,
            y: v1.y - v0.y,
            z: v1.z - v0.z
        };

        const edge2 = {
            x: v2.x - v0.x,
            y: v2.y - v0.y,
            z: v2.z - v0.z
        };

        // Produto vetorial (normal)
        const normal = {
            x: edge1.y * edge2.z - edge1.z * edge2.y,
            y: edge1.z * edge2.x - edge1.x * edge2.z,
            z: edge1.x * edge2.y - edge1.y * edge2.x
        };

        // Normaliza
        const length = Math.sqrt(normal.x ** 2 + normal.y ** 2 + normal.z ** 2);
        if (length > 0) {
            normal.x /= length;
            normal.y /= length;
            normal.z /= length;
        }

        // Escreve faceta
        stl += `  facet normal ${normal.x.toExponential(6)} ${normal.y.toExponential(6)} ${normal.z.toExponential(6)}\n`;
        stl += `    outer loop\n`;
        stl += `      vertex ${v0.x.toExponential(6)} ${v0.y.toExponential(6)} ${v0.z.toExponential(6)}\n`;
        stl += `      vertex ${v1.x.toExponential(6)} ${v1.y.toExponential(6)} ${v1.z.toExponential(6)}\n`;
        stl += `      vertex ${v2.x.toExponential(6)} ${v2.y.toExponential(6)} ${v2.z.toExponential(6)}\n`;
        stl += `    endloop\n`;
        stl += `  endfacet\n`;
    }

    stl += `endsolid ${solidName}\n`;
    return stl;
}

/**
 * Faz download de um arquivo
 * @param {string} content - Conteúdo do arquivo
 * @param {string} filename - Nome do arquivo
 * @param {string} mimeType - Tipo MIME
 */
export function downloadFile(content, filename, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    
    link.href = url;
    link.download = filename;
    link.style.display = 'none';
    
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    setTimeout(() => {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, 100);
}

/**
 * Exporta e faz download em formato JSON
 * @param {Object} surfaceData - Dados da superfície
 * @param {Object} profileData - Dados do perfil
 */
export function exportJSON(surfaceData, profileData) {
    const json = exportToJSON(surfaceData, profileData);
    const timestamp = Date.now();
    downloadFile(json, `revolution-surface-${timestamp}.json`, 'application/json');
}

/**
 * Exporta e faz download em formato OBJ
 * @param {Object} surfaceData - Dados da superfície
 */
export function exportOBJ(surfaceData) {
    const obj = exportToOBJ(surfaceData);
    const timestamp = Date.now();
    downloadFile(obj, `revolution-surface-${timestamp}.obj`, 'text/plain');
}

/**
 * Exporta e faz download em formato STL
 * @param {Object} surfaceData - Dados da superfície
 */
export function exportSTL(surfaceData) {
    const stl = exportToSTL(surfaceData);
    const timestamp = Date.now();
    downloadFile(stl, `revolution-surface-${timestamp}.stl`, 'text/plain');
}
